// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    FormBody: typeof import('./src/components/FormBody.vue')['default']
    FromBody: typeof import('./src/components/FromBody.vue')['default']
    Input: typeof import('./src/components/plugins/Input.vue')['default']
    PluginConfig: typeof import('./src/components/PluginConfig.vue')['default']
    Plugins: typeof import('./src/components/Plugins.vue')['default']
    PluginsCard: typeof import('./src/components/PluginsCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
