// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Cascader: typeof import('./src/components/plugins/Cascader.vue')['default']
    Checkbox: typeof import('./src/components/plugins/Checkbox.vue')['default']
    ColorPicker: typeof import('./src/components/plugins/ColorPicker.vue')['default']
    Counter: typeof import('./src/components/plugins/Counter.vue')['default']
    DatePicker: typeof import('./src/components/plugins/DatePicker.vue')['default']
    Dropdown: typeof import('./src/components/plugins/Dropdown.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRate: typeof import('element-plus/es')['ElRate']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FormBody: typeof import('./src/components/FormBody.vue')['default']
    Input: typeof import('./src/components/plugins/Input.vue')['default']
    PluginConfig: typeof import('./src/components/PluginConfig.vue')['default']
    PluginsCard: typeof import('./src/components/PluginsCard.vue')['default']
    Radio: typeof import('./src/components/plugins/Radio.vue')['default']
    Rate: typeof import('./src/components/plugins/Rate.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slider: typeof import('./src/components/plugins/Slider.vue')['default']
    Switch: typeof import('./src/components/plugins/Switch.vue')['default']
    Textarea: typeof import('./src/components/plugins/Textarea.vue')['default']
    TimePicker: typeof import('./src/components/plugins/TimePicker.vue')['default']
    Upload: typeof import('./src/components/plugins/Upload.vue')['default']
  }
}

export {}
